
export const LANGUAGES = [
    { id: 'en.asad', label: 'English (Asad)', native: 'English' },
    { id: 'ur.jalandhry', label: 'Urdu (Jalandhry)', native: 'اردو' },
    { id: 'id.indonesian', label: 'Indonesian', native: 'Bahasa Indonesia' },
    { id: 'tr.ates', label: 'Turkish', native: 'Türkçe' },
    { id: 'fr.hamidullah', label: 'French', native: 'Français' },
    { id: 'ru.kuliev', label: 'Russian', native: 'Русский' },
    { id: 'de.aburida', label: 'German', native: 'Deutsch' },
    { id: 'es.cortes', label: 'Spanish', native: 'Español' },
    { id: 'bn.bengali', label: 'Bengali', native: 'বাংলা' },
    { id: 'hi.hindi', label: 'Hindi', native: 'हिन्दी' },
    { id: 'pt.elhayek', label: 'Portuguese', native: 'Português' },
    { id: 'ja.japanese', label: 'Japanese', native: '日本語' },
    { id: 'ms.basmeih', label: 'Malay', native: 'Bahasa Melayu' },
    { id: 'fa.fooladvand', label: 'Persian', native: 'فارسی' },
    { id: 'it.piccardo', label: 'Italian', native: 'Italiano' },
    { id: 'nl.keyzer', label: 'Dutch', native: 'Nederlands' },
    { id: 'th.thai', label: 'Thai', native: 'ไทย' },
    { id: 'ko.korean', label: 'Korean', native: '한국어' },
    { id: 'zh.jian', label: 'Chinese (Simplified)', native: '简体中文' },
];
